# Generated by Django 5.1.3 on 2024-11-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_player_gamer_tag_alter_player_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='kills_blue',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='kills_red',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
